### ISSUE TITLE
Create a readme or a documentation

### ISSUE THREAD

**Issue by babeuloula** [Hraph/SyliusPaygreenPlugin#3]
Hello, 

In order to use in the good way your lib, can you create a documentation ? Reverse engineering with test folder is not a good way :D 

Thanks

**Comment by Hraph** [comment]
Ahah,
Simply because this project is still a work in progress and I didn't think anyone would use it so quickly. Thanks for your feedbacks!

**Comment by babeuloula** [comment]
OK I understand. Keep going, you doing a great job.

**Comment by babeuloula** [comment]
Thanks for the readme.
